// <auto-generated />
using System;
using Adarsh_Studio.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Adarsh_Studio.Migrations
{
    [DbContext(typeof(AdarshSdbContext))]
    [Migration("20250130193222_AddVerificationCodeToLoginMasters")]
    partial class AddVerificationCodeToLoginMasters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Adarsh_Studio.Models.BookingMaster", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ClientName")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_On");

                    b.Property<int?>("CurrentCity")
                        .HasColumnType("int");

                    b.Property<string>("EmailId")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<int?>("LocationOfShooting")
                        .HasColumnType("int");

                    b.Property<long?>("MobileNo")
                        .HasColumnType("bigint");

                    b.Property<int?>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ShootingDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("BookingId");

                    b.HasIndex("CurrentCity");

                    b.HasIndex("LocationOfShooting");

                    b.ToTable("BookingMaster", (string)null);
                });

            modelBuilder.Entity("Adarsh_Studio.Models.CityMaster", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_On");

                    b.HasKey("CityId");

                    b.ToTable("CityMaster", (string)null);
                });

            modelBuilder.Entity("Adarsh_Studio.Models.EnquiryMaster", b =>
                {
                    b.Property<int>("EnquiryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnquiryId"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("EmailId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MobNo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("QueryMsg")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("EnquiryId");

                    b.ToTable("EnquiryMaster", (string)null);
                });

            modelBuilder.Entity("Adarsh_Studio.Models.FeedbackMaster", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("EmailId")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FeedbackMsg")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<long>("MobileNo")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("StarRating")
                        .HasColumnType("int");

                    b.Property<string>("TitleOfFeedback")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.HasKey("FeedbackId");

                    b.ToTable("FeedbackMaster", (string)null);
                });

            modelBuilder.Entity("Adarsh_Studio.Models.LoginMaster", b =>
                {
                    b.Property<string>("AdminId")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("AdminPass")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Admin_Pass");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_On");

                    b.Property<bool?>("IsBlocked")
                        .HasColumnType("bit")
                        .HasColumnName("Is_Blocked");

                    b.Property<DateTime?>("LastLoginDt")
                        .HasColumnType("datetime")
                        .HasColumnName("Last_Login_DT");

                    b.Property<int?>("LoginCount")
                        .HasColumnType("int")
                        .HasColumnName("Login_Count");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("Updated_On");

                    b.HasKey("AdminId");

                    b.ToTable("LoginMaster", (string)null);
                });

            modelBuilder.Entity("Adarsh_Studio.Models.ServiceMaster", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<int?>("Budget")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_On");

                    b.Property<string>("Description")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("DiscountedRate")
                        .HasColumnType("int");

                    b.Property<string>("Exclusions")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Inclusions")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("Updated_On");

                    b.HasKey("ServiceId");

                    b.ToTable("ServiceMaster", (string)null);
                });

            modelBuilder.Entity("Adarsh_Studio.Models.ServicePicMaster", b =>
                {
                    b.Property<int>("PicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PicId"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_On");

                    b.Property<string>("PicFileName")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("PicFolderName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<double?>("PicSizeInKb")
                        .HasColumnType("float")
                        .HasColumnName("PicSize_InKB");

                    b.Property<string>("PicType")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("PicId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServicePicMaster", (string)null);
                });

            modelBuilder.Entity("Adarsh_Studio.Models.UpdatesMaster", b =>
                {
                    b.Property<int>("UpdateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UpdateId"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdateMsg")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.HasKey("UpdateId");

                    b.ToTable("UpdatesMaster", (string)null);
                });

            modelBuilder.Entity("Adarsh_Studio.Models.BookingMaster", b =>
                {
                    b.HasOne("Adarsh_Studio.Models.CityMaster", "CurrentCityNavigation")
                        .WithMany("BookingMasterCurrentCityNavigations")
                        .HasForeignKey("CurrentCity")
                        .HasConstraintName("FK_BookingMaster_CityMaster1");

                    b.HasOne("Adarsh_Studio.Models.CityMaster", "LocationOfShootingNavigation")
                        .WithMany("BookingMasterLocationOfShootingNavigations")
                        .HasForeignKey("LocationOfShooting")
                        .HasConstraintName("FK_BookingMaster_CityMaster");

                    b.Navigation("CurrentCityNavigation");

                    b.Navigation("LocationOfShootingNavigation");
                });

            modelBuilder.Entity("Adarsh_Studio.Models.ServicePicMaster", b =>
                {
                    b.HasOne("Adarsh_Studio.Models.ServiceMaster", "Service")
                        .WithMany("ServicePicMasters")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK_ServicePicMaster_ServiceMaster");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Adarsh_Studio.Models.CityMaster", b =>
                {
                    b.Navigation("BookingMasterCurrentCityNavigations");

                    b.Navigation("BookingMasterLocationOfShootingNavigations");
                });

            modelBuilder.Entity("Adarsh_Studio.Models.ServiceMaster", b =>
                {
                    b.Navigation("ServicePicMasters");
                });
#pragma warning restore 612, 618
        }
    }
}
